spark.jars.ivy=/tmp/.ivy2
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

# timezome
spark.sql.session.timeZone=Asia/Jakarta

# Spark catalog name
spark.sql.defaultCatalog=warehouse

# Iceberg REST Catalog -> Apache Polaris
spark.sql.catalog.warehouse=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.warehouse.type=rest
spark.sql.catalog.warehouse.uri=http://polaris:8181/api/catalog

# Polaris catalog name
spark.sql.catalog.warehouse.warehouse=warehouse

# Polaris authentication
spark.sql.catalog.warehouse.credential=root:s3cret
spark.sql.catalog.warehouse.scope=PRINCIPAL_ROLE:ALL
spark.sql.catalog.warehouse.oauth2-server-uri=http://polaris:8181/api/catalog/v1/oauth/tokens
spark.sql.catalog.warehouse.rest.auth.type=oauth2
spark.sql.catalog.warehouse.rest-metrics-reporting-enabled=false

# Iceberg FileIO
spark.sql.catalog.warehouse.io-impl=org.apache.iceberg.aws.s3.S3FileIO

# SeaweedFS S3
spark.sql.catalog.warehouse.s3.endpoint=http://s3:8333
spark.sql.catalog.warehouse.s3.path-style-access=true
spark.sql.catalog.warehouse.s3.access-key-id=admin
spark.sql.catalog.warehouse.s3.secret-access-key=password

spark.sql.catalog.warehouse.s3.region=us-east-1
spark.sql.catalog.warehouse.client.region=us-east-1
spark.sql.catalog.warehouse.header.Polaris-Realm=POLARIS

# SPARK HISTORY SERVER
spark.eventLog.enabled=true
spark.eventLog.dir=file:///opt/spark/events

spark.history.fs.logDirectory=file:///opt/spark/events
spark.history.ui.port=18081
spark.eventLog.rolling.enabled=false

spark.scheduler.mode=FAIR