spark.jars.ivy=/tmp/.ivy2

spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

# Spark catalog name
spark.sql.defaultCatalog=polaris

# Iceberg REST Catalog -> Apache Polaris
spark.sql.catalog.polaris=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.polaris.type=rest
spark.sql.catalog.polaris.uri=http://polaris:8181/api/catalog

# Polaris catalog name
spark.sql.catalog.polaris.warehouse=warehouse

# Polaris authentication
spark.sql.catalog.polaris.credential=root:s3cret
spark.sql.catalog.polaris.scope=PRINCIPAL_ROLE:ALL

# Explicit OAuth endpoint
spark.sql.catalog.polaris.oauth2-server-uri=http://polaris:8181/api/catalog/v1/oauth/tokens

# Iceberg FileIO
spark.sql.catalog.polaris.io-impl=org.apache.iceberg.aws.s3.S3FileIO

# SeaweedFS S3
spark.sql.catalog.polaris.s3.endpoint=http://s3:8333
spark.sql.catalog.polaris.s3.path-style-access=true
spark.sql.catalog.polaris.s3.access-key-id=admin
spark.sql.catalog.polaris.s3.secret-access-key=password

spark.sql.catalog.polaris.s3.region=us-east-1
spark.sql.catalog.polaris.client.region=us-east-1

# SPARK HISTORY SERVER
spark.eventLog.enabled=true
spark.eventLog.dir=file:///opt/spark/events

spark.history.fs.logDirectory=file:///opt/spark/events
spark.history.ui.port=18081
spark.eventLog.rolling.enabled=false