seeds:
  - name: seed_provinces
    description: Infromation provinces names on indonesian
    columns:
      - name: name
      - name: name_en
    config:
      enabled: true
  
  - name: seed_cities
    description: Infromation cities names on indonesian
    columns:
      - name: name
    config:
      enabled: true
