version: 2

sources:
  - name: warehouse_bronze
    database: iceberg
    schema: bronze
    tables:
      - name: jobs

  - name: warehouse_silvers
    database: iceberg
    schema: silvers
    tables:
      - name: job_skills_list
      - name: job_majors_list
      