version: 2

sources:
  - name: bronze
    database: iceberg
    schema: bronze
    tables:
      - name: jobs
      - name: jobs_entries
        identifier: "jobs$entries"

  - name: silver
    database: iceberg
    schema: silver
    tables:
      - name: job_skills_list
      - name: job_majors_list

  - name: seed
    database: iceberg
    schema: seed
    tables:
      - name: seed_villages
      
  